import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center py-14 px-8">
          <h1 className="text-6xl font-bold">Quoted</h1>
          <p className="m-2">Where Wit Meets Submit!</p>
          {children}
          <p className="mt-auto">Nathan Huey 2023</p>
        </main>
      </body>
    </html>
  );
}
